APPLICATION = driver_adxl362
include ../Makefile.tests_common

FEATURES_REQUIRED = periph_spi
FEATURES_REQUIRED = periph_gpio

USEMODULE += adxl362
USEMODULE += xtimer

CFLAGS_OPT  ?= -O0

include $(RIOTBASE)/Makefile.include
